d /storage 0755 root root -
d /storage/config 0700 ashipaos ashipaos -
d /storage/state 0700 ashipaos ashipaos -
d /storage/cache 0755 ashipaos ashipaos -
d /storage/downloads 0750 ashipaos ashipaos -
d /storage/thumbnails 0755 ashipaos ashipaos -
d /storage/logs 0750 ashipaos ashipaos -
d /storage/app 0755 root root -
