#!/usr/bin/env python3
import json
import subprocess
import gi
gi.require_version('Gtk', '4.0')
from gi.repository import Gtk, GLib

class Settings(Gtk.Application):
    def __init__(self): super().__init__(application_id='appliance-settings')
    def do_activate(self):
        win=Gtk.ApplicationWindow(application=self); win.set_title('Network Settings'); win.set_default_size(900,520)
        box=Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=18); box.set_margin_top(36); box.set_margin_bottom(36); box.set_margin_start(48); box.set_margin_end(48)
        title=Gtk.Label(label='Network Settings'); title.set_xalign(0); title.add_css_class('title-1'); box.append(title)
        self.status=Gtk.Label(); self.status.set_xalign(0); box.append(self.status)
        scan=Gtk.Button(label='Rescan Wi-Fi'); scan.connect('clicked', lambda _: self.refresh()); box.append(scan)
        close=Gtk.Button(label='Close'); close.connect('clicked', lambda _: win.close()); box.append(close)
        win.set_child(box); win.present(); self.refresh()
    def refresh(self):
        try: out=subprocess.check_output(['nmcli','-t','-f','DEVICE,TYPE,STATE,CONNECTION','device'], text=True, timeout=3)
        except Exception as e: out=f'Network status unavailable: {e}'
        self.status.set_text(out)
app=Settings(); app.run([])
