#!/usr/bin/env python3
"""Generate the A95X F3 Air IR keymap (ir-keytable TOML) from the stock DTB.

Source: map "cyxtech-remote-a95x" in the stock firmware's meson1.dtb
(NEC, custom code 0xdf00). Usage: gen-ir-keymap.py <meson1.dtb> <out.toml>
"""
import re
import subprocess
import sys

MAP_NAME = "cyxtech-remote-a95x"
# Linux input-event-codes for the keys this remote sends.
NAMES = {2: "KEY_1", 3: "KEY_2", 4: "KEY_3", 5: "KEY_4", 6: "KEY_5", 7: "KEY_6", 8: "KEY_7",
         9: "KEY_8", 10: "KEY_9", 11: "KEY_0", 14: "KEY_BACKSPACE", 28: "KEY_ENTER",
         102: "KEY_HOME", 103: "KEY_UP", 105: "KEY_LEFT", 106: "KEY_RIGHT", 108: "KEY_DOWN",
         113: "KEY_MUTE", 114: "KEY_VOLUMEDOWN", 115: "KEY_VOLUMEUP", 116: "KEY_POWER",
         139: "KEY_MENU"}
# Appliance-UI changes: Back is the app's ESC; Android's 122/123 page keys.
OVERRIDES = {158: "KEY_ESC", 122: "KEY_PAGEUP", 123: "KEY_PAGEDOWN"}
HEADER = """\
# A95X F3 Air IR remote for the mainline meson-ir receiver (loaded by ir-keytable).
# Generated by layers/layer1-rootfs/scripts/gen-ir-keymap.py from the stock
# firmware map "cyxtech-remote-a95x" in layers/layer2-image/files/a95x-f3-air/
# meson1.dtb: NEC, custom code 0xdf00 (address byte 0x00, then 0xdf), which
# Linux reports as NEC-extended scancode 0xdfCC; the byte-swapped form 0xdf00CC
# is listed too. Back -> ESC (the app's back key); 122/123 -> PAGEUP/PAGEDOWN;
# vendor-only keys are omitted.
[[protocols]]
name = "a95x-f3-air"
protocol = "nec"
[protocols.scancodes]
"""


def main(dtb, out):
    dts = subprocess.run(["dtc", "-I", "dtb", "-O", "dts", dtb], check=True,
                         capture_output=True, text=True).stdout
    block = re.search(r'mapname = "' + re.escape(MAP_NAME) + r'";(.*?)\};', dts, re.S)
    if not block:
        raise SystemExit(f"{MAP_NAME} not found in {dtb}")
    body = block.group(1)
    if "customcode = <0xdf00>;" not in body:
        raise SystemExit("unexpected custom code for " + MAP_NAME)
    entries = [int(v, 16) for v in re.search(r"keymap = <([^>]*)>", body).group(1).split()]
    keys = []
    for entry in entries:
        command, code = entry >> 16, entry & 0xFFFF
        name = OVERRIDES.get(code) or NAMES.get(code)
        if name:
            keys.append((command, name))
    lines = [f'0xdf{c:02x} = "{n}"' for c, n in keys] + [f'0xdf00{c:02x} = "{n}"' for c, n in keys]
    with open(out, "w", encoding="utf-8") as stream:
        stream.write(HEADER + "\n".join(lines) + "\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    main(*sys.argv[1:])
